server:
  port: 9001
spring:
  application:
    name: server01
  cloud:
    nacos:
      discovery:
        server-addr: 172.23.35.16:8848
#        ip: @nacos.ip@
        group: gateway
        namespace: gateway