server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.23.35.16:8848
        group: gateway
        namespace: gateway
    gateway:
      discovery:
        #是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能
        enabled: true
        #开启小写，#路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
        lower-case-service-id: true
      routes:
        #第一个服务的路由规则
        - id: service01
          # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
          uri: lb://service01
          predicates:
            #以后访问 http://127.0.0.1:13008/serverone/one/hello/two，ip:端口/自定义path/接口地址
            - Path=/service01/**
          #第二个服务的路由规则
        - id: service02
          uri: lb://service02
          predicates:
            - Path=/service02/**
