server:
  port: 9002
spring:
  application:
    name: service02
  cloud:
    nacos:
      discovery:
        server-addr: 43.138.12.110:8848
#        ip: @nacos.ip@
        group: gateway
        namespace: gateway